In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,34,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((44,44))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,55)

array([ 0.        ,  0.18518519,  0.37037037,  0.55555556,  0.74074074,
        0.92592593,  1.11111111,  1.2962963 ,  1.48148148,  1.66666667,
        1.85185185,  2.03703704,  2.22222222,  2.40740741,  2.59259259,
        2.77777778,  2.96296296,  3.14814815,  3.33333333,  3.51851852,
        3.7037037 ,  3.88888889,  4.07407407,  4.25925926,  4.44444444,
        4.62962963,  4.81481481,  5.        ,  5.18518519,  5.37037037,
        5.55555556,  5.74074074,  5.92592593,  6.11111111,  6.2962963 ,
        6.48148148,  6.66666667,  6.85185185,  7.03703704,  7.22222222,
        7.40740741,  7.59259259,  7.77777778,  7.96296296,  8.14814815,
        8.33333333,  8.51851852,  8.7037037 ,  8.88888889,  9.07407407,
        9.25925926,  9.44444444,  9.62962963,  9.81481481, 10.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(2)

array([0.27137801, 0.68065859])

In [21]:
np.random.randint(1,34)

30

In [22]:
np.random.rand(1,1)

array([[0.01492303]])

In [23]:
np.random.randn(2)


array([ 0.15162747, -1.6401856 ])

In [24]:
np.random.randn(5,10)

array([[-0.26210581,  0.33126371, -0.2881348 , -0.82777171,  0.60308291,
         0.34000687,  0.5020184 , -1.55480864, -0.71647291, -0.5373519 ],
       [-0.11114028,  0.88629312,  1.23034156,  0.35235091, -0.18599597,
        -2.56199339,  1.09038966,  0.43122307,  0.53305602, -0.97896477],
       [-0.21787215, -0.45546181,  0.22771319,  0.11767219, -0.10161431,
        -1.55640157, -0.74131907, -0.56841457,  0.63627282,  1.88100621],
       [-0.37339859, -1.25525535, -0.6407427 , -0.80287638,  0.78418592,
         0.02067685, -0.45216518, -0.62637595, -0.60335007, -0.46498767],
       [ 0.37561521,  0.01154929, -0.70055786, -0.45920047, -1.22935038,
         0.40316913,  0.47920344,  1.4920355 ,  1.45957728,  1.12913996]])

In [25]:
np.random.randint(12,100)

71

In [26]:
np.random.randint(1,100,50)

array([25,  9, 96, 92, 39, 58,  8, 95, 38, 63, 35, 83, 79, 24, 82, 89, 56,
       14, 46, 16, 12, 30, 19,  6, 26,  5, 27, 54,  4, 93, 68, 97,  9, 80,
       50, 94, 99, 66, 71, 31, 84, 14, 63, 23, 41, 87, 71, 91,  4,  3])

In [27]:
arr = np.arange(24)
ranarr = np.random.randint(0,50,10)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [29]:
ranarr

array([45, 45,  9, 46, 34, 10, 17, 34, 28,  9])

In [31]:
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [32]:
ranarr

array([45, 45,  9, 46, 34, 10, 17, 34, 28,  9])

In [33]:
ranarr.max()

46

In [34]:
ranarr.argmax()

3

In [35]:
ranarr.min()

9

In [36]:
ranarr.argmin()

2

In [37]:
arr.shape

(24,)

In [42]:
arr.reshape(1,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [43]:
arr.reshape(1,24).shape

(1, 24)

In [44]:
arr.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [45]:
arr.reshape(24,1).shape


(24, 1)

In [46]:
arr.dtype

dtype('int32')